In [1]:
!pwd

/home/alan_khang/dev/mirror3d


In [23]:
import numpy as np
import matplotlib.pyplot as plt
import cv2
import os
from glob import glob
import numpy as np
from sklearn.cluster import KMeans
import json
from pathlib import Path

In [ ]:
json_path = Path("./mirror3d_input/mp3d/train_10_coarse_normal_mirror.json")

with json_path.open("r") as f:
    data = json.load(f)

def collect_key_values(obj, target_key):
    values = []
    if isinstance(obj, dict):
        for k, v in obj.items():
            if k == target_key:
                values.append(v)
            values.extend(collect_key_values(v, target_key))
    elif isinstance(obj, list):
        for item in obj:
            values.extend(collect_key_values(item, target_key))
    return values

mirror_normals = collect_key_values(data, "mirror_normal_camera")

print(f"Found {len(mirror_normals)} values.")

Found 3428 values.


In [46]:
X = np.array(mirror_normals, dtype=float)

#X = X[~np.isnan(X).any(axis=1)]

kmeans = KMeans(n_clusters=10)
labels = kmeans.fit_predict(X)

centers = kmeans.cluster_centers_

print("Cluster centers:\n", centers)
print("Inertia:", kmeans.inertia_)
print("Counts per cluster:", np.bincount(labels, minlength=10))

Cluster centers:
 [[ 7.86203129e-02 -4.33989214e-03 -9.90011427e-01]
 [-5.48988928e-01  1.40651689e-02 -8.20870900e-01]
 [ 7.90019945e-01  7.73984999e-03 -5.78582866e-01]
 [-2.55376002e-01 -3.74949302e-03 -9.60715892e-01]
 [-9.85379650e-01 -6.08866863e-03 -7.55076925e-02]
 [-5.09206790e-02 -6.22601780e-01 -7.04036040e-01]
 [ 8.73697942e-02  6.21989685e-01 -7.12488432e-01]
 [ 4.74570037e-01 -4.74835136e-03 -8.68485429e-01]
 [-8.32837602e-01  2.06199793e-04 -5.26335553e-01]
 [ 9.75826567e-01  6.88385318e-03 -1.26594523e-01]]
Inertia: 96.4794687267005
Counts per cluster: [635 515 340 459 167 121 114 568 339 170]


In [47]:
y = np.load('./mirror3d/mirror3dnet/config/mp3d_kmeans_normal_10.npy')

In [48]:
y

array([[ 0.97047234,  0.01551118,  0.09865975],
       [-0.46621135,  0.03246798, -0.85917467],
       [-0.03985072, -0.623527  , -0.69895273],
       [ 0.81480014,  0.00897133, -0.5305273 ],
       [-0.9607818 , -0.00759295,  0.12416411],
       [-0.8310606 ,  0.00475491, -0.52176166],
       [ 0.472176  ,  0.02172534,  0.84041697],
       [-0.27829406, -0.0069779 ,  0.9060332 ],
       [ 0.45470482,  0.03879919, -0.864669  ],
       [-0.00991482,  0.03423819, -0.97703177]], dtype=float32)

In [49]:
centers.tolist()

[[0.07862031292354976, -0.004339892142729416, -0.9900114272728969],
 [-0.5489889275502784, 0.014065168948285885, -0.8208709004544449],
 [0.7900199452832218, 0.007739849991698783, -0.5785828662425041],
 [-0.2553760021390861, -0.003749493017719818, -0.9607158924738713],
 [-0.9853796498720447, -0.006088668634664467, -0.07550769247444644],
 [-0.05092067903026767, -0.6226017796567213, -0.704036039503072],
 [0.08736979424021069, 0.6219896845925633, -0.7124884318902127],
 [0.4745700373645986, -0.004748351363263489, -0.8684854288758835],
 [-0.8328376023918367, 0.00020619979275636517, -0.5263355525600146],
 [0.9758265670864134, 0.006883853177231343, -0.12659452278814742]]

In [50]:
img = cv2.imread('./data/Mirror-Glass_Segmentation.v10i.coco-segmentation/int_mask/train/oak_front_frame_0000026_jpg.rf.8a3c7bcb8d36ad63c58b159a868a29d2.png', cv2.IMREAD_UNCHANGED)

In [51]:
np.unique(img)

array([0, 1, 2, 3, 4, 5], dtype=uint16)

In [57]:
!ls ./data/Mirror-Glass_Segmentation.v10i.coco-segmentation/output/train/anno_pcd | wc -l

48


In [53]:
x = np.identity(10)

In [55]:
x[x.astype(bool)]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [83]:
img = cv2.imread('/home/alan_khang/dev/mirror3d/dataset/nyu/mirror_instance_mask_precise/718.png', cv2.IMREAD_UNCHANGED)

In [84]:
np.unique(img)

array([0, 1, 2, 3], dtype=uint16)